background:
  mode: gradient # gradient / solid
  solid_color: "#333333FF"
  grad_color_0: "#495766FF"
  grad_color_1: "#60656bFF"

hex_map_engine:
  chunk_size: 16 # a chunk has CHUNK_SIZE * CHUNK_SIZE units
  data_dimensions: 4 # data size for each hexagon unit (currently only [r, g, b, a])
  hex_radius: 1.0 # the radius of each hexagon unit
  hex_height: 0.5 # unused; reserved for future 3d scene

hex_map_custom:
  outline_color: "#FFFFFF6A"
  default_cell_color: "#888888FF"
  outline_width: 1.0

hex_map_view:
  min_zoom: 0.005
  max_zoom: 5.0

hex_map_shaders:
  unit:
    vertex: "src/shaders/hex/vsh.glsl"
    fragment: "src/shaders/hex/fsh.glsl"
  background:
    vertex: "src/shaders/background/vsh.glsl"
    fragment: "src/shaders/background/fsh.glsl"
  cursor:
    vertex: "src/shaders/cursor/vsh.glsl"
    fragment: "src/shaders/cursor/fsh.glsl"
